services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network


  go-app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: